# Generated by Django 5.1.3 on 2024-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_working',
            field=models.BooleanField(),
        ),
    ]
