# Generated by Django 5.1.3 on 2024-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_emp_age_alter_emp_emp_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_working',
            field=models.BooleanField(default=True),
        ),
    ]
